version: "3.8"

services:
  frontend:
    build: ./mini_app
    depends_on:
      - 'database'
      
    ports:
      - "3000:3000"
    networks:
      - app-network
  
  api:
    build: ./server
    depends_on:
      - 'database'
      
    ports:
      - "3001:3001"
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: db-container
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge